### PR TITLE
add jscoverage support

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Comment by rphillips** [comment]
How do we want to propagate the coverage results up from the spawned test to the main whiskey application? I am thinking of an RPC REST service in the main whiskey process. Overkill?

**Comment by Kami** [comment]
We have two options:
1. Each test process writes test results to a temporary file and at the end, main process parses those files to produce a final report
2. We could start a new TCP server in the main process which listens on a unix socket and all the child processes would connect to it and post serialized coverage results back to it (JSON)

I am leaning towards the option #2 which will also be used for sending back the test results in v0.3.0.

**Comment by rphillips** [comment]
After more work on this, I have discovered _$jscoverage doesn't serialize cleanly down to a JSON object, so propagating the results to the parent process is problematic until a solution is found.

**Comment by Kami** [comment]
Yeah, looks like there are cyclic references in this object and JSON.stringify can't handle it.

Using something like this should work - https://gist.github.com/946847 (result: https://gist.github.com/946849).

**Comment by rphillips** [comment]
Nice. Thanks

On Thu, Apr 28, 2011 at 12:46 PM, Kami
reply@reply.github.com
wrote:

**Comment by rphillips** [comment]
Kami: I vote on me finishing this up for the master branch, and the logic ported to v0.3.0. Should be a bit cleaner with the domain socket service I saw in 0.3.0.

Thoughts?

**Comment by Kami** [comment]
Sounds OK.

I will probably port Cast tests to the new test format today to make sure I haven't introduced any regressions. After I finish this, I can start working on porting coverage support to 0.3.0.

Also please let me know when this branch is ready to be reviewed and merged.

**Comment by Kami** [comment]
Coverage support has been integrated into Whiskey 0.3.0.

Thanks.

**Pull request closed without merging**
