### PR TITLE
Whiskey - log (at info level) when a process is stopped

### PR DESCRIPTION
**Pull request by lakshmi-kannan**

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
I found a .swp file which I am deleting with this commit. I did not see any .gitignore files. Should I create one?

**Comment by pquerna** [comment]
`.runner.js.swp` probably shouldn't be committed?

**Comment by Kami** [comment]
@lakshmi-kannan For files like that I usually just use global (`~/.gitignore`) and not per repo `.gitignore` file.

Even better, you would probably benefit by modifying your vim config to not store swap files in the same directory as the actual file. For example:

```
set directory=~/.tmp/vim/
set backupdir=~/.tmp/vim/
```

**Comment by Kami** [comment]
Besides the committed swap file issue, LGTM,  +1

**Comment by lakshmi-kannan** [comment]
@Kami: Thanks. The .swp file was in the repo. I am just deleting it with the commit. 

Also, I have this in my .vimrc : set nobackup
I just realized vim still creates a .swp file. I'll check what's going wrong.

**Comment by lakshmi-kannan** [comment]
Apparently, I need these in my .vimrc

set nowritebackup  #only in case you don't want a backup file while editing
set noswapfile     #no swap files

I am going with your suggestion. Thanks.

**Pull request merged**
